#!/usr/bin/env bash

source lib/common.sh

if [ "$(id -u)" -eq 0 ]; then
    echo "This script must not be run as root or with sudo." >&2
    exit 1
fi

IMAGE_TO_BUILD=${BMROS_IMAGE_BB_REF_PROD}
BASE_DIR=${PWD}
CPU_LIMIT=""

update_last_build_recipe() {
    echo -e "${1} " >> "${BASE_DIR}/.last_build_recipe"
}

resolve_cpu_limit() {
    local requested_cpu_limit="$1"
    local host_cpu_count

    host_cpu_count="$(nproc)"

    case "${requested_cpu_limit}" in
        n-1|N-1)
            if (( host_cpu_count > 1 )); then
                echo $((host_cpu_count - 1))
            else
                echo 1
            fi
            ;;
        all|ALL)
            echo "${host_cpu_count}"
            ;;
        ''|*[!0-9]*)
            echo "ERROR: CPU limit must be a positive integer, 'n-1', or 'all'." >&2
            exit 1
            ;;
        *)
            if (( requested_cpu_limit < 1 )); then
                echo "ERROR: CPU limit must be at least 1." >&2
                exit 1
            fi
            echo "${requested_cpu_limit}"
            ;;
    esac
}

write_cpu_limit_config() {
    local resolved_cpu_limit="$1"
    local auto_conf="conf/auto.conf"
    local tmp_auto_conf="${auto_conf}.tmp"
    local begin_marker="# BEGIN BMROS CPU LIMIT"
    local end_marker="# END BMROS CPU LIMIT"

    if [[ -f "${auto_conf}" ]]; then
        awk -v begin="${begin_marker}" -v end="${end_marker}" '
            $0 == begin { skip = 1; next }
            $0 == end { skip = 0; next }
            !skip { print }
        ' "${auto_conf}" > "${tmp_auto_conf}"
    else
        : > "${tmp_auto_conf}"
    fi

    {
        cat "${tmp_auto_conf}"
        if [[ -s "${tmp_auto_conf}" ]]; then
            echo
        fi
        cat <<EOF
${begin_marker}
# Generated by build-bmros.sh. Re-run with --cpus to change this value.
BB_NUMBER_THREADS = "${resolved_cpu_limit}"
PARALLEL_MAKE = "-j ${resolved_cpu_limit}"
PARALLEL_MAKEINST = "-j ${resolved_cpu_limit}"
${end_marker}
EOF
    } > "${auto_conf}"

    rm -f "${tmp_auto_conf}"
}

usage() {
    echo
    echo "Usage: $0 [options]"
    echo "Options:"
    echo
    echo -e "  -c, --${POKY_CORE_IMG_MIN}"    
    echo -e "  -b, --${BMROS_IMAGE_BB_REF_PROD}\t\t(Production - default)"
    echo -e "  -d, --${BMROS_IMAGE_BB_REF_DEBUG}\t\t(Debug)"      
    echo -e "  -v, --${BMROS_IMAGE_BB_REF_VANILLA}\t(Non-Debug)"
    echo      
    echo "  -u, --update-poky-meta-bare-metal-router-layer-only"
    echo "  -r, --remove-update-poky-meta-bare-metal-router-layer"
    echo
    echo "  -j, --cpus <count|n-1|all>"
    echo "      Limit BitBake and recipe parallelism. Use 'n-1' to leave one CPU free."
    echo
    exit 1
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in

        -b|--bare-metal-router)
            IMAGE_TO_BUILD="${BMROS_IMAGE_BB_REF_PROD}"
            shift
            ;;

        -v|--bare-metal-router-vanilla)
            IMAGE_TO_BUILD="${BMROS_IMAGE_BB_REF_VANILLA}"
            shift
            ;;

        -d|--bare-metal-router-debug|--bare-metal-router-dev)
            IMAGE_TO_BUILD="${BMROS_IMAGE_BB_REF_DEBUG}"
            shift
            ;;            

        -c|--core-image-minimal)
            IMAGE_TO_BUILD="${POKY_CORE_IMG_MIN}"
            shift
            ;;

        -j|--cpus|--cpu-limit)
            if [[ $# -lt 2 ]]; then
                echo "Missing value for $1"
                usage
            fi
            CPU_LIMIT="$(resolve_cpu_limit "$2")"
            shift 2
            ;;

        -u|--update-poky-meta-bare-metal-router-layer-only|--update-bare-metal-layer-only)
            ./update-layers.sh
            shift
            ;;

        -r|--remove-update-poky-meta-bare-metal-router-layer)
            
            echo
            echo "Remove directories:"
            echo " * poky/layers/meta-bare-metal-router" 
            echo " * poky/build-bmros/tmp"
            echo
            echo "Removing there directory will remove any changed outside of the standard install"
            read -p "Are you sure (y/n): " confirm

            if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
                rm -rf poky/layers/meta-bare-metal-router
                rm -rf poky/build-bmros/tmp

            else
                echo
                echo "Removal of teh following directories canceled:"
                echo " * poky/layers/meta-bare-metal-router" 
                echo " * poky/build-bmros/tmp"
                echo               
                exit 1
            fi
            
            ./update-layers.sh
            
            shift
            ;;

        -h|--help)
            usage
            exit
            ;;

        *)
            echo "Unknown option: $1"
            usage
            exit
            ;;
    esac
done

start_time=$(get_epoch_timestamp)
display_banner "Building ${IMAGE_TO_BUILD}"

BASE_DIR=${PWD}
POKY_DIR="${BASE_DIR}/${POKY_DIR_NAME}"

check_directory "$POKY_DIR" || { 
    echo "ERROR: Directory $POKY_DIR not found"
    echo "ERROR: Run: . ${BASE_DIR}/install-yocto-poky.sh"
    echo
    exit 1
}

cd "$POKY_DIR" 

source "layers/openembedded-core/oe-init-build-env" ${BMROS_BUILD_DIR_NAME}

if [[ -n "$CPU_LIMIT" ]]; then
    write_cpu_limit_config "${CPU_LIMIT}"
    echo "Configured BitBake CPU limit: ${CPU_LIMIT}"
fi

if [[ -n "$IMAGE_TO_BUILD" ]]; then
    display_banner "Start Build: $IMAGE_TO_BUILD"
    bitbake -k $IMAGE_TO_BUILD || handle_error "Build ${IMAGE_TO_BUILD} Failed"
    update_last_build_recipe "${IMAGE_TO_BUILD}"
fi

if check_directory "${BASE_DIR}/downloads"; then
    echo "Adding ${BASE_DIR}/downloads to reduce time for future build"
    echo "!!!!DO NOT REMOVE!!!! -> ${BASE_DIR}/downloads"
fi

elapsed_time=$(( $(get_epoch_timestamp) - start_time ))

display_banner "BUILD (${IMAGE_TO_BUILD}) COMPLETE - Build Elapse Time: $elapsed_time seconds"
